fix: remove unused fields
htmlacademy-nodejs/1470531-typoteka-3 pull request #18
Opened 2020-10-10 11:33 UTC by ivanov-alexey

2020-10-14 21:42 UTC, html-malex commented on src/backend/data-service/article.js
> +        ORDER BY "commentsCount" DESC
У меня есть подозрение что `ORDER BY "commentsCount" DESC` выдаст ошибку на неизвестное поле `commentsCount` - проверь, пожалуйста.
Кстати, если я не ошибаюсь, в Postgres можно для ORDER BY использовать числа - например, `ORDER BY 2 DESC` будет означать, что нужно выполнить обратную сортировку по второму полю в SELECT

2020-10-14 21:42 UTC, html-malex requested changes
См. комментарии

2020-10-15 03:11 UTC, ivanov-alexey commented on src/backend/data-service/article.js
> +        ORDER BY "commentsCount" DESC
Я сначала проверил запрос в консоли, все норм. Вебшторм мне сам подсказал "commentsCount" подставить. Плюс проверил все ли работает на самом проекте - все работает)

2020-10-15 04:44 UTC, html-malex approved these changes

2020-10-15 04:44 UTC, merged